{% set version = "0.0.4" %}

package:
  name: esgf-search
  version: {{ version }}

source:
  path: .

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  host:
    - python
    - requests
    - pandas
  run:
    - python
    - requests
    - pandas

test:
  imports:
    - esgf_search
    - esgf_search.esgf
    - esgf_search.facets

about:
  home: https://github.com/esgf-nimbus/jupyterhub-config
  summary: 'Simple ESGF search interface.'
